---
spring:
  datasource:
    url: "jdbc:oracle:thin:@192.168.100.78/FREEPDB1"
    username: "PERSONS_DB"
    password: "Lider0ne"
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: "none"
    properties:
      hibernate:
        query:
          in_clause_parameter_padding: true
        criteria:
          literal_handling_mode: "bind"
        jdbc:
          fetch_size: 100
          batch_size: 100
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
  docker:
    compose:
      enabled: false
decorator:
  datasource:
    datasource-proxy:
      logging: "slf4j"
      count-query: false
      json-format: false
      multiline: true
      query:
        enable-logging: true
        log-level: "info"
        logger-name: "net.ttddyy.dsproxy.listener.logging.SLF4JQueryLoggingListener"
      slow-query:
        enable-logging: true
        log-level: "info"
        logger-name: "net.ttddyy.dsproxy.listener.logging.SLF4JSlowQueryListener"
        threshold: 300
    flexy-pool:
      acquiring-strategy:
        increment-pool:
          max-overflow-pool-size: 10
          timeout-millis: 500
        retry:
          attempts: 2
      metrics:
        reporter:
          jmx:
            enabled: false
