---
spring:
  datasource:
    url: "jdbc:oracle:thin:@localhost/FREEPDB1"
    username: "PERSONS_DB"
    password: "Lider0ne"
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: "none"
    properties:
      hibernate:
        query:
          in_clause_parameter_padding: true
        criteria:
          literal_handling_mode: "bind"
        jdbc:
          fetch_size: 100
          batch_size: 100
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
