-- liquibase formatted sql

-- changeset ehayik:create-persons-addresses-tables

CREATE SEQUENCE PERSON_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE PERSONS
(
    PERSON_ID       NUMBER(10)    NOT NULL
        CONSTRAINT PERSONS_PK PRIMARY KEY,
    FIRST_NAME      VARCHAR2(100) NOT NULL,
    LAST_NAME       VARCHAR2(100) NOT NULL,
    BIRTH_DATE      DATE          NOT NULL,
    GENDER          NUMBER(1)     NOT NULL,
    PHONE           VARCHAR2(20),
    EMAIL           VARCHAR2(50),
    CREATED_ON      TIMESTAMP     NOT NULL,
    LAST_UPDATED_ON TIMESTAMP     NOT NULL,
    ADDRESS_ID      NUMBER(10)    NOT NULL
);

CREATE TABLE PERSON_GENDER_INFO
(
    GENDER_ID          NUMBER(1) PRIMARY KEY NOT NULL,
    GENDER_NAME        CHAR                  NOT NULL,
    GENDER_DESCRIPTION VARCHAR2(25)          NOT NULL

);

CREATE SEQUENCE ADDRESS_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE ADDRESSES
(
    ADDRESS_ID      NUMBER(10)    NOT NULL
        CONSTRAINT ADDRESSES_PK PRIMARY KEY,
    STREET          VARCHAR2(250) NOT NULL,
    BUILDING_NUMBER VARCHAR2(100) NOT NULL,
    CITY            VARCHAR2(100) NOT NULL,
    COUNTRY         VARCHAR2(100) NOT NULL,
    ZIP_CODE        VARCHAR2(20)  NOT NULL,
    CREATED_ON      TIMESTAMP     NOT NULL,
    LAST_UPDATED_ON TIMESTAMP     NOT NULL
);

ALTER TABLE PERSONS
    ADD CONSTRAINT FK_PERSONS_ADDRESS_ID
        FOREIGN KEY (ADDRESS_ID)
            REFERENCES ADDRESSES (ADDRESS_ID);

INSERT INTO PERSON_GENDER_INFO
VALUES (0, 'M', 'male');
INSERT INTO PERSON_GENDER_INFO
VALUES (1, 'F', 'female');